pipeline {
    agent any
    tools {
        jdk 'Java 17'
        gradle 'Gradle 8.7'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                script {
                    // Imprimir información de diagnóstico
                    sh 'echo $JAVA_HOME'
                    sh 'java -version'
                    sh 'gradle --version'
                }
                dir("${env.WORKSPACE}") {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build -x test'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh "sudo cp ${env.WORKSPACE}/build/libs/etalent-backend-0.0.1-SANPSHOT.jar /opt/proyectos/etalent-backend.jar"
                    sh 'sudo systemctl restart etalent-backend.service'
                }
            }
        }
    }
    post {
        success {
            echo 'Despliegue exitoso'
        }
        failure {
            echo 'Hubo un error en el despliegue'
        }
    }
}